### ISSUE TITLE
Compilation build on mac fails

### ISSUE THREAD

**Issue by azimov** [OHDSI/bayes-bridge#19]
Hi @aki-nishimura @msuchard I have an issue when attempting install in different environments with both pip and setup.py. This appears to be something to do with the Cython extension used:

using build_ext:

```
python setup.py build_ext --inplace             
/Users/jamie/PycharmProjects/bayesbridge/bayes-bridge/setup.py:4: DeprecationWarning: 

  `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
  of the deprecation of `distutils` itself. It will be removed for
  Python >= 3.12. For older Python versions it will remain present.
  It is recommended to use `setuptools < 60.0` for those Python versions.
  For more details, see:
    https://numpy.org/devdocs/reference/distutils_status_migration.html 


  from numpy.distutils.misc_util import get_info
Compiling bayesbridge/random/tilted_stable/tilted_stable.pyx because it changed.
Compiling bayesbridge/random/polya_gamma/polya_gamma.pyx because it changed.
Compiling bayesbridge/random/uniform/uniform.pyx because it changed.
[1/3] Cythonizing bayesbridge/random/polya_gamma/polya_gamma.pyx
/Users/jamie/PycharmProjects/bayesbridge/venv/lib/python3.11/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /Users/jamie/PycharmProjects/bayesbridge/bayes-bridge/bayesbridge/random/polya_gamma/polya_gamma.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
import cython
import numpy as np
cimport numpy as np
from numpy.random import PCG64
from numpy.random.bit_generator cimport BitGenerator
from scipy_ndtr cimport log_ndtr as normal_logcdf
^
------------------------------------------------------------

bayesbridge/random/polya_gamma/polya_gamma.pyx:9:0: 'scipy_ndtr.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
import cython
import numpy as np
cimport numpy as np
from numpy.random import PCG64
from numpy.random.bit_generator cimport BitGenerator
from scipy_ndtr cimport log_ndtr as normal_logcdf
^
------------------------------------------------------------

bayesbridge/random/polya_gamma/polya_gamma.pyx:9:0: 'scipy_ndtr/log_ndtr.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...

    cdef double calc_prob_to_right(self, double tilt, double exp_rate):
        cdef double log_mass_expo \
            = - log(exp_rate) - exp_rate * self.THRESHOLD + log(.25 * M_PI)
        cdef double log_mass_invg_1 \
            = - tilt + normal_logcdf(
                       ^
------------------------------------------------------------

bayesbridge/random/polya_gamma/polya_gamma.pyx:130:23: 'normal_logcdf' is not a constant, variable or function identifier

Error compiling Cython file:
------------------------------------------------------------
...
            = - log(exp_rate) - exp_rate * self.THRESHOLD + log(.25 * M_PI)
        cdef double log_mass_invg_1 \
            = - tilt + normal_logcdf(
                (self.THRESHOLD * tilt - 1.) / sqrt(self.THRESHOLD))
        cdef double log_mass_invg_2 \
            = tilt + normal_logcdf(
                     ^
------------------------------------------------------------

bayesbridge/random/polya_gamma/polya_gamma.pyx:133:21: 'normal_logcdf' is not a constant, variable or function identifier
Traceback (most recent call last):
  File "/Users/jamie/PycharmProjects/bayesbridge/bayes-bridge/setup.py", line 64, in <module>
    ext_modules=cythonize(ext_modules),
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamie/PycharmProjects/bayesbridge/venv/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
    cythonize_one(*args)
  File "/Users/jamie/PycharmProjects/bayesbridge/venv/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: bayesbridge/random/polya_gamma/polya_gamma.pyx


```

Note that this is on mac (intel) but I have also experienced the same problem on windows. Any advice on how to resolve this? I have installed the latest versions of Cython and scipy available in pypi.

**Comment by azimov** [comment]
Ok - I think I figured it out and I will try to publish steps to reproduce.

It appears you need to manually compile the poly_gamma file:

```
cd bayesbridge/random/polya_gamma
# not needed on windows
export MACOSX_DEPLOYMENT_TARGET=10.5
python build_ext
```

This creates the object files.

I then went back to the root dir and ran ```python setup.py install``` as usual.

I will attempt to make this more straightforward in the standard setup.py that should fix the pip installation process.

**Comment by aki-nishimura** [comment]
Hm, I am not seeing the issue on my mac (Catalina) with Python 3.11.4, Cython 3.0.0, Numpy 1.25.2, and setuptools 68.0.0. But I appreciate the report and I'd be happy to find out what exactly are going wrong in your environment and how we can fix it.

**Comment by aki-nishimura** [comment]
@azimov The commit https://github.com/OHDSI/bayes-bridge/commit/1e598a6618b41f64c7e507be7a512ad5f17b07db should fix the Cython compilation issue. The old code works fine on my Mac M2 if I use Cython 0.29 and [the release note](https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html) mentions some backward incompatible changes, so I guess the error was caused the Cython's 0.29 -> 3.0 update. 

Many thanks to @chinandrew for suggesting the solution.
